name: Nocobase Build Test

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - 'main'
      - 'develop'
    paths:
      - 'packages/**'
      - '.github/workflows/nocobase-build-test.yml'
  pull_request:
    branches:
      - '**'
    paths:
      - 'packages/**'
      - '.github/workflows/nocobase-build-test.yml'

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Checkout pro-plugins
        continue-on-error: true # 外部开发者提交 PR 的时候因为没有权限这里会报错，为了能够继续执行后续步骤，所以这里设置为 continue-on-error: true
        uses: actions/checkout@v4
        with:
          repository: nocobase/pro-plugins
          ref: main
          path: packages/pro-plugins
          ssh-key: ${{ secrets.SUBMODULE_SSH_KEY }}
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'
      - run: yarn --frozen-lockfile
      - run: yarn build
        env:
          __E2E__: true # e2e will be reusing this workflow, so we need to set this flag to true
      - uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: |
            packages/**/es/
            packages/**/lib/
            packages/**/dist/
            !packages/**/node_modules/**
    timeout-minutes: 30
